// cgo -godefs types_illumos.go | go run mkpost.go
// Code generated by the command above; see README.md. DO NOT EDIT.

//go:build amd64 && illumos
// +build amd64,illumos

package unix

const (
	TUNNEWPPA = 0x540001
	TUNSETPPA = 0x540002
)
